config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "users#index"

  post '/create', to: 'users#create'

  delete '/destroy', to: 'users#destroy'

  post '/match_create', to: 'matches#create'

  get '/match_show', to: 'matches#show'

  delete '/match_destroy', to: 'matches#destroy'

  post '/player_create', to: 'players#create'

  delete '/destroy_player', to: 'players#destroy'

  put '/add_goal_scored', to: 'players#add_goal_scored'

  put '/subtract_goal_scored', to: 'players#subtract_goal_scored'

  get '/team_show', to: 'teams#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  
  self.abstract_class = true
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :home_squad, class_name: "Squad"
  belongs_to :away_squad, class_name: "Squad"
  
  validates :match_result, presence: true
end
    

app/models/player.rb
class Player < ApplicationRecord

  belongs_to :user 
  belongs_to :squad
    
  def username
    user.username
  end

  validates :goals_scored, presence: true
  validate :validate_goals_scored
    def validate_goals_scored
      if goals_scored && goals_scored < 0 
        errors.add(:goals_scored, 'can not be less than 0')
      end
    end
end
  

app/models/squad.rb
class Squad < ApplicationRecord
  has_many :players 
  has_one :home_match, :class_name => "Match", :foreign_key => "home_squad_id"
  has_one :away_match, :class_name => "Match", :foreign_key => "away_squad_id"
  has_many :users, through: :players
  belongs_to :team

  validates :team_name, presence: true
end

app/models/team.rb
class Team < ApplicationRecord  
  has_many :squads   

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  has_many :players 
  has_many :squads, through: :players

  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def create 
    alert = MatchCreateService.call(match_params["home_team_name"], match_params["away_team_name"], match_params["home_score"], match_params["away_score"])
    if alert.present?
      flash[:alert] = alert
      redirect_to action: "index", controller: "users"
    else
      redirect_to action: "index", controller: "users"
    end
  end
        
  def destroy
    MatchDestroyService.call(params["match_id"])
        
    redirect_to action: "index", controller: "users"
  end

  def show
    @match = Match.find params["match_id"]
    @home_squad = @match.home_squad 
    @away_squad = @match.away_squad
    @home_players = @home_squad.players.order(:created_at).to_a
    @away_players = @away_squad.players.order(:created_at).to_a
    @other_users = User.all.to_a - @home_players.map { |player| player.user } - @away_players.map { |player| player.user }
  end

  def match_params
    params.require(:match).permit("home_team_name", "away_team_name", "home_score", "away_score")
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def create
    match = Match.find params["match_id"]
    alert = PlayerCreateService.call(params["user_id"], params["squad_id"])
    if alert.present?
      flash[:alert] = alert
      redirect_to action: "show", controller: "matches", match_id: match.id
    else
      redirect_to action: "show", controller: "matches", match_id: match.id
    end
  end

  def destroy
    match = Match.find params["match_id"]
    PlayerDestroyService.call(params["player_id"])

    redirect_to action: "show", controller: "matches", match_id: match.id
  end

  def add_goal_scored 
    match = Match.find params["match_id"]
    AddGoalService.call(params["player_id"])
    
    redirect_to action: "show", controller: "matches", match_id: match.id
  end

  def subtract_goal_scored  
    match = Match.find params["match_id"]
    alert = SubtractGoalService.call(params["player_id"])
    if alert.present?
      flash[:alert] = alert
      redirect_to action: "show", controller: "matches", match_id: match.id
    else
      redirect_to action: "show", controller: "matches", match_id: match.id
    end
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController  
  def show
    @team = Team.find params["team_id"]
    @home_matches = Match.joins(:home_squad).where(squads: { team_id: @team.id }).to_a
    @away_matches = Match.joins(:away_squad).where(squads: { team_id: @team.id }).to_a
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    alert = UserCreateService.call(params["username"])
    if alert.present?
      flash[:alert] = alert
      redirect_to action: "index"
    else
      redirect_to action: "index"
    end
  end

  def destroy
    user = User.find params["user_id"]
    user.players.destroy_all
    user.destroy!
    redirect_to action: "index"
  end

  def index 
    @users = User.all.order(:created_at)
    @matches = Match.all.order(:created_at)
    @players = Player.all.order(:created_at)
    @squads = Squad.all.order(:created_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>pilka</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="<%= root_path %>">Piłka</a>
  </nav>
  
  
  <div class="container">
  <div class="row">
    <% if alert %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <div class="text-dark"><%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div> 
      </div>
    <% end %>   
  </div>
  </div>
  



    <%= yield %>
  </body>
</html>

app/views/matches/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-2">
      <p class="font-weight-bold">Home team</p>
    </div>
    <div class="col-sm-2">
      <p class="font-weight-bold">Away team</p>
    </div>
    <div class="col-sm-2">
      <p class="font-weight-bold">Score</p>
    </div>
    <div class="col-md-auto">
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-2">
      <%= @match.home_squad.team_name %>
    </div>
    <div class="col-sm-2">
      <%= @match.away_squad.team_name %>
    </div>
    <div class="col-sm-2">
      <%= @match.match_result %>
    </div>
    <div class="col-md-auto">
    </div>
  </div>
</div>

<p>
</p>

<% if @home_players.present? %>
  <div class="container">
    <div class="row">
      <div class="col-sm-2">
        <p class="font-weight-bold">Home team players</p>
      </div>
      <div class="col-sm-2">
        <p class="font-weight-bold">Goals scored</p>
      </div>
      <div class="col-sm-2">
      </div>
      <div class="col-md-auto">
      </div>
    </div>
  </div>
<% end %>

<div class="container"> 
  <% @home_players.each do |player| %>
    <div class="row"> 
      <div class="col-sm-2">
        <%= player.username %>
      </div>
      <div class="col-sm-2">
        <%= player.goals_scored %>
      </div>
      <div class="col-sm-2"> 
      </div>
      <div class="col-md-auto">

        <form class="form-inline" action="/add_goal_scored" method=post style="display: inline;"> 
          <input type="hidden" value="put" name="_method">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token() %>"/>
          <input type="hidden" name="match_id" value="<%= @match.id %>">  
          <input type="hidden" name="player_id" value="<%= player.id %>">
          <button type="submit" class="btn btn-success btn-sm">Add goal</button>
        </form>

        <form class="form-inline" action="/subtract_goal_scored" method=post style="display: inline;">
          <input type="hidden" value="put" name="_method">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token() %>"/>
          <input type="hidden" name="match_id" value="<%= @match.id %>">
          <input type="hidden" name="player_id" value="<%= player.id %>">
          <button type="submit" class="btn btn-danger btn-sm">Subtract goal</button>
        </form>
        
        <form class="form-inline" action="/destroy_player" method=post style="display: inline;">
          <input type="hidden" value="delete" name="_method">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token() %>"/>
          <input type="hidden" name="match_id" value="<%= @match.id %>">
          <input type="hidden" name="player_id" value="<%= player.id %>">
          <button type="submit" class="btn btn-outline-dark btn-sm">Remove player</button>
        </form>
      </div>
    </div>
  <% end %>
</div> 

<p>
</p>

<div class="container">
  <div class="row">
    <div class="col-sm-2">
    </div>
    <div class="col-sm-2">
    </div>
    <div class="col-sm-2"> 
    </div>
    <div class="col-md-auto">
      <form class="form-inline" action="/player_create" method=post style="display: inline;">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <input type="hidden" name="match_id" value="<%= @match.id %>">
        <input type="hidden" name="squad_id" value="<%= @match.home_squad.id %>">
        <div class="input-group">
        <select class="custom-select" name="user_id">
          <option selected disabled>Choose...</option>
          <% @other_users.each do |user| %>
            <option value="<%= user.id %>"><%= user.username %></option>
          <% end %>
        </select>
        <div class="input-group-append">
        <button type="submit" class="btn btn-outline-dark btn-sm">Add player to home team</button>
        </div>
        </div>
      </form>
    </div>   
  </div>
</div>

<p>
</p>

<% if @away_players.present? %>
  <div class="container">
    <div class="row">
      <div class="col-sm-2">
        <p class="font-weight-bold">Away team players</p>
      </div>
      <div class="col-sm-2">
        <p class="font-weight-bold">Goals scored</p>
      </div>
      <div class="col-sm-2">
      </div>
      <div class="col-md-auto">
      </div>
    </div>
  </div>
<% end %>

<div class="container"> 
  <% @away_players.each do |player| %>
    <div class="row"> 
      <div class="col-sm-2">
        <%= player.username %>
      </div>
      <div class="col-sm-2">
        <%= player.goals_scored %>
      </div>
      <div class="col-sm-2"> 
      </div>
      <div class="col-md-auto">

        <form class="form-inline" action="/add_goal_scored" method=post style="display: inline;"> 
          <input type="hidden" value="put" name="_method">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token() %>"/>
          <input type="hidden" name="match_id" value="<%= @match.id %>">  
          <input type="hidden" name="player_id" value="<%= player.id %>">
          <button type="submit" class="btn btn-success btn-sm">Add goal</button>
        </form>

        <form class="form-inline" action="/subtract_goal_scored" method=post style="display: inline;">
          <input type="hidden" value="put" name="_method">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token() %>"/>
          <input type="hidden" name="match_id" value="<%= @match.id %>">
          <input type="hidden" name="player_id" value="<%= player.id %>">
          <button type="submit" class="btn btn-danger btn-sm">Subtract goal</button>
        </form>
        
        <form class="form-inline" action="/destroy_player" method=post style="display: inline;">
          <input type="hidden" value="delete" name="_method">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token() %>"/>
          <input type="hidden" name="match_id" value="<%= @match.id %>">  
          <input type="hidden" name="player_id" value="<%= player.id %>">
          <button type="submit" class="btn btn-outline-dark btn-sm">Remove player</button>
        </form>
      </div>
    </div>
  <% end %>
</div> 

<p>
</p>

<div class="container">
  <div class="row">
    <div class="col-sm-2">
    </div>
    <div class="col-sm-2">
    </div>
    <div class="col-sm-2"> 
    </div>
    <div class="col-md-auto">
      <form class="form-inline" action="/player_create" method=post style="display: inline;">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <input type="hidden" name="match_id" value="<%= @match.id %>">
        <input type="hidden" name="squad_id" value="<%= @match.away_squad.id %>">
        <div class="input-group">
        <select class="custom-select" name="user_id">
          <option selected disabled>Choose...</option>
          <% @other_users.each do |user| %>
            <option value="<%= user.id %>"><%= user.username %></option>
          <% end %>
        </select>
        <div class="input-group-append">
        <button type="submit" class="btn btn-outline-dark btn-sm">Add player to away team</button>
        </div>
        </div>
      </form>
    </div>
  </div>
</div>


  

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
      <form action="/create" method=post>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <label for="username" class="font-weight-bold">Add user</label><br>
        <input type="text" class="form-control" name="username" placeholder="Enter username">
        <button type="submit" class="btn btn-info">Submit</button>
      </form>
    </div>   
  </div>
</div>

<p>
</p>

<div class="container">
  <div class="row">
    <div class="col-sm-2">
      <p class="font-weight-bold">Name</p>
    </div>
    <div class="col-sm-2">
      <p class="font-weight-bold">Goals count</p>
    </div>
    <div class="col-sm-2">
      <p class="font-weight-bold">Matches played</p>
    </div>
    <div class="col-md-auto">
    </div>
  </div>
</div>

<div class="container">
  
  <% @users.each do |user| %>
    <div class="row">
      <div class="col-sm-2">
        <%= user.username %>
      </div>
      <div class="col-sm-2">
        <%= user.goals_count %>
      </div>
      <div class="col-sm-2">
        <%= user.match_count %>
      </div>
      <div class="col-md-auto">
        <form class="form-inline" action="/destroy" method="post" style="display: inline;">
          <input type="hidden" value="delete" name="_method">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token() %>"/>
          <input type="hidden" name="user_id" value="<%= user.id %>">
          <button type="submit" class="btn btn-outline-dark btn-sm">Remove user</button>
        </form>
      </div>
    </div>
  <% end %>
</div>

<p>
</p>

<div class="container">
  <div class="row">
    <div class="col-3">
      <form action="/match_create" method=post>
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <label for="home_team_name" class="font-weight-bold">Add match teams</label><br>
        <input type="text" class="form-control" name="match[home_team_name]" placeholder="Enter home team">
        <p>
        </p>
        <input type="text" class="form-control" name="match[away_team_name]" placeholder="Enter away team">
        <p>
        </p>
        <label for="home_score" class="font-weight-bold">Add score</label><br>
        <div class="form-row">
          <div class="col">
            <input type="number" min="0" max="150" class="form-control" name="match[home_score]" placeholder="Home">
          </div>
          <div class="col-sm-1">
          <input type="text" readonly class="form-control-plaintext text-center" id=":" value=":">
          </div>
          <div class="col">
            <input type="number" min="0" max="150" class="form-control" name="match[away_score]" placeholder="Away">
          </div>
        </div>
        <button type="submit" class="btn btn-info float-right">Submit</button>
      </form>
    </div>   
  </div>
</div>

<p>
</p>

<div class="container">
  <div class="row">
    <div class="col-sm-2">
      <p class="font-weight-bold">Home team</p>
    </div>
    <div class="col-sm-2">
      <p class="font-weight-bold">Away team</p>
    </div>
    <div class="col-sm-2">
      <p class="font-weight-bold">Score</p>
    </div>
    <div class="col-md-auto">
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col">
    </div>
  </div>
  <% @matches.each do |match| %>
    <div class="row">
      <div class="col-sm-2">
        <%= link_to match.home_squad.team_name, team_show_path(team_id: match.home_squad.team.id), method: "get", class: "text-dark" %>
      </div>
      <div class="col-sm-2">
        <%= link_to match.away_squad.team_name, team_show_path(team_id: match.away_squad.team.id), method: "get", class: "text-dark" %>
      </div>
      <div class="col-sm-2">
        <%= match.match_result %>
      </div>
      <div class="col-md-auto">
        <form class="form-inline" action="/match_destroy" method=post style="display: inline;">
        <input type="hidden" value="delete" name="_method">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token() %>"/>
        <input type="hidden" name="match_id" value="<%= match.id %>">
        <button type="submit" class="btn btn-outline-dark btn-sm">Remove match result</button>
        </form>
        <%= link_to "Match details", match_show_path(match_id: match.id), method: "get", class: "btn btn-primary" %>   
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div>
  <ul>
  <% @users.each do |user| %>
    <li>
    <%= user.username %>, <%= user.goals_count %>, <%= user.minutes_played %>

      <form action="/add_goal" >
        <input type="hidden" name="user_id" value="<%= user.id %>">
        <input type="submit" value="Add goal">

      </form>

      <form action="/subtract_goal" >
        <input type="hidden" name="user_id" value="<%= user.id %>">
        <input type="submit" value="Subtract goal">
  
      </form>
  
    </li>
  <% end %>
  </ul>
</div>



<form action="/create" >
  <label for="username"> Username:</label><br>
  <input type="text" name="username"><br>
  <input type="submit" value="Submit">

</form>